import Head from 'next/head'
import Link from 'next/link'
import { NextPage } from 'next'
import utilStyles from '../styles/utils.module.css'
import Layout, { siteTitle } from '../components/layout'
import { getSortedPostsData } from '../lib/posts'
import Date from '@/components/date'

type PostsData = {
  allPostsData: Array<{
    id: string,
    date: string,
    title: string,
  }>
}

const Home : NextPage<PostsData>  = ({ allPostsData }) => {
  return (
    <Layout home>
      <Head>
        <title>Learn Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={utilStyles.headingMd}>
        <p>Hello, I&apos;m keigo-0314</p>
        <p>
          (This is a sample website - you’ll be building a site like this on{' '}
            <a href="https://nextjs.org/learn">our Next.js tutorial</a>.
          )
        </p>
        <h1 className="title">
          Read <Link href="/posts/first-post">this page!</Link>
        </h1>
      </section>
      <section className={`${utilStyles.headingMd} ${utilStyles.padding1px}`}>
        <h2 className={utilStyles.headingLg}>Blog</h2>
        <ul className={utilStyles.list}>
          {allPostsData.map(({ id, date, title }) => (
            <li className={utilStyles.listItem} key={id}>
              <Link href={`posts/${id}`}>{title}</Link>
              <br />
              <small className={utilStyles.lightText}>
                <Date dateString={date}></Date>
              </small>
            </li>
          ))}
        </ul>
      </section>
    </Layout>
  )
}

export const getStaticProps =  async () => {
  const allPostsData = getSortedPostsData();
  
  return {
    props: {
      allPostsData,
    },
  }
}

export default Home
